package io.objectbox.performanceapp.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import io.objectbox.performanceapp.greendao.SimpleEntity;
import io.objectbox.performanceapp.greendao.SimpleEntityNotNull;
import io.objectbox.performanceapp.greendao.SimpleEntityNotNullIndexed;

import io.objectbox.performanceapp.greendao.SimpleEntityDao;
import io.objectbox.performanceapp.greendao.SimpleEntityNotNullDao;
import io.objectbox.performanceapp.greendao.SimpleEntityNotNullIndexedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simpleEntityDaoConfig;
    private final DaoConfig simpleEntityNotNullDaoConfig;
    private final DaoConfig simpleEntityNotNullIndexedDaoConfig;

    private final SimpleEntityDao simpleEntityDao;
    private final SimpleEntityNotNullDao simpleEntityNotNullDao;
    private final SimpleEntityNotNullIndexedDao simpleEntityNotNullIndexedDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simpleEntityDaoConfig = daoConfigMap.get(SimpleEntityDao.class).clone();
        simpleEntityDaoConfig.initIdentityScope(type);

        simpleEntityNotNullDaoConfig = daoConfigMap.get(SimpleEntityNotNullDao.class).clone();
        simpleEntityNotNullDaoConfig.initIdentityScope(type);

        simpleEntityNotNullIndexedDaoConfig = daoConfigMap.get(SimpleEntityNotNullIndexedDao.class).clone();
        simpleEntityNotNullIndexedDaoConfig.initIdentityScope(type);

        simpleEntityDao = new SimpleEntityDao(simpleEntityDaoConfig, this);
        simpleEntityNotNullDao = new SimpleEntityNotNullDao(simpleEntityNotNullDaoConfig, this);
        simpleEntityNotNullIndexedDao = new SimpleEntityNotNullIndexedDao(simpleEntityNotNullIndexedDaoConfig, this);

        registerDao(SimpleEntity.class, simpleEntityDao);
        registerDao(SimpleEntityNotNull.class, simpleEntityNotNullDao);
        registerDao(SimpleEntityNotNullIndexed.class, simpleEntityNotNullIndexedDao);
    }
    
    public void clear() {
        simpleEntityDaoConfig.clearIdentityScope();
        simpleEntityNotNullDaoConfig.clearIdentityScope();
        simpleEntityNotNullIndexedDaoConfig.clearIdentityScope();
    }

    public SimpleEntityDao getSimpleEntityDao() {
        return simpleEntityDao;
    }

    public SimpleEntityNotNullDao getSimpleEntityNotNullDao() {
        return simpleEntityNotNullDao;
    }

    public SimpleEntityNotNullIndexedDao getSimpleEntityNotNullIndexedDao() {
        return simpleEntityNotNullIndexedDao;
    }

}
