package io.objectbox.performanceapp.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import io.objectbox.performanceapp.greendao.SimpleEntity;
import io.objectbox.performanceapp.greendao.SimpleEntityIndexed;

import io.objectbox.performanceapp.greendao.SimpleEntityDao;
import io.objectbox.performanceapp.greendao.SimpleEntityIndexedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simpleEntityDaoConfig;
    private final DaoConfig simpleEntityIndexedDaoConfig;

    private final SimpleEntityDao simpleEntityDao;
    private final SimpleEntityIndexedDao simpleEntityIndexedDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simpleEntityDaoConfig = daoConfigMap.get(SimpleEntityDao.class).clone();
        simpleEntityDaoConfig.initIdentityScope(type);

        simpleEntityIndexedDaoConfig = daoConfigMap.get(SimpleEntityIndexedDao.class).clone();
        simpleEntityIndexedDaoConfig.initIdentityScope(type);

        simpleEntityDao = new SimpleEntityDao(simpleEntityDaoConfig, this);
        simpleEntityIndexedDao = new SimpleEntityIndexedDao(simpleEntityIndexedDaoConfig, this);

        registerDao(SimpleEntity.class, simpleEntityDao);
        registerDao(SimpleEntityIndexed.class, simpleEntityIndexedDao);
    }
    
    public void clear() {
        simpleEntityDaoConfig.clearIdentityScope();
        simpleEntityIndexedDaoConfig.clearIdentityScope();
    }

    public SimpleEntityDao getSimpleEntityDao() {
        return simpleEntityDao;
    }

    public SimpleEntityIndexedDao getSimpleEntityIndexedDao() {
        return simpleEntityIndexedDao;
    }

}
