package io.objectbox.performanceapp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SIMPLE_ENTITY_NOT_NULL_INDEXED".
*/
public class SimpleEntityNotNullIndexedDao extends AbstractDao<SimpleEntityNotNullIndexed, Long> {

    public static final String TABLENAME = "SIMPLE_ENTITY_NOT_NULL_INDEXED";

    /**
     * Properties of entity SimpleEntityNotNullIndexed.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property SimpleBoolean = new Property(1, boolean.class, "simpleBoolean", false, "SIMPLE_BOOLEAN");
        public final static Property SimpleByte = new Property(2, byte.class, "simpleByte", false, "SIMPLE_BYTE");
        public final static Property SimpleShort = new Property(3, short.class, "simpleShort", false, "SIMPLE_SHORT");
        public final static Property SimpleInt = new Property(4, int.class, "simpleInt", false, "SIMPLE_INT");
        public final static Property SimpleLong = new Property(5, long.class, "simpleLong", false, "SIMPLE_LONG");
        public final static Property SimpleFloat = new Property(6, float.class, "simpleFloat", false, "SIMPLE_FLOAT");
        public final static Property SimpleDouble = new Property(7, double.class, "simpleDouble", false, "SIMPLE_DOUBLE");
        public final static Property SimpleString = new Property(8, String.class, "simpleString", false, "SIMPLE_STRING");
        public final static Property SimpleByteArray = new Property(9, byte[].class, "simpleByteArray", false, "SIMPLE_BYTE_ARRAY");
    }


    public SimpleEntityNotNullIndexedDao(DaoConfig config) {
        super(config);
    }
    
    public SimpleEntityNotNullIndexedDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SIMPLE_ENTITY_NOT_NULL_INDEXED\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"SIMPLE_BOOLEAN\" INTEGER NOT NULL ," + // 1: simpleBoolean
                "\"SIMPLE_BYTE\" INTEGER NOT NULL ," + // 2: simpleByte
                "\"SIMPLE_SHORT\" INTEGER NOT NULL ," + // 3: simpleShort
                "\"SIMPLE_INT\" INTEGER NOT NULL ," + // 4: simpleInt
                "\"SIMPLE_LONG\" INTEGER NOT NULL ," + // 5: simpleLong
                "\"SIMPLE_FLOAT\" REAL NOT NULL ," + // 6: simpleFloat
                "\"SIMPLE_DOUBLE\" REAL NOT NULL ," + // 7: simpleDouble
                "\"SIMPLE_STRING\" TEXT," + // 8: simpleString
                "\"SIMPLE_BYTE_ARRAY\" BLOB);"); // 9: simpleByteArray
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_SIMPLE_ENTITY_NOT_NULL_INDEXED_SIMPLE_STRING ON SIMPLE_ENTITY_NOT_NULL_INDEXED" +
                " (\"SIMPLE_STRING\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SIMPLE_ENTITY_NOT_NULL_INDEXED\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SimpleEntityNotNullIndexed entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getSimpleBoolean() ? 1L: 0L);
        stmt.bindLong(3, entity.getSimpleByte());
        stmt.bindLong(4, entity.getSimpleShort());
        stmt.bindLong(5, entity.getSimpleInt());
        stmt.bindLong(6, entity.getSimpleLong());
        stmt.bindDouble(7, entity.getSimpleFloat());
        stmt.bindDouble(8, entity.getSimpleDouble());
 
        String simpleString = entity.getSimpleString();
        if (simpleString != null) {
            stmt.bindString(9, simpleString);
        }
 
        byte[] simpleByteArray = entity.getSimpleByteArray();
        if (simpleByteArray != null) {
            stmt.bindBlob(10, simpleByteArray);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SimpleEntityNotNullIndexed entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getSimpleBoolean() ? 1L: 0L);
        stmt.bindLong(3, entity.getSimpleByte());
        stmt.bindLong(4, entity.getSimpleShort());
        stmt.bindLong(5, entity.getSimpleInt());
        stmt.bindLong(6, entity.getSimpleLong());
        stmt.bindDouble(7, entity.getSimpleFloat());
        stmt.bindDouble(8, entity.getSimpleDouble());
 
        String simpleString = entity.getSimpleString();
        if (simpleString != null) {
            stmt.bindString(9, simpleString);
        }
 
        byte[] simpleByteArray = entity.getSimpleByteArray();
        if (simpleByteArray != null) {
            stmt.bindBlob(10, simpleByteArray);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public SimpleEntityNotNullIndexed readEntity(Cursor cursor, int offset) {
        SimpleEntityNotNullIndexed entity = new SimpleEntityNotNullIndexed( //
            cursor.getLong(offset + 0), // id
            cursor.getShort(offset + 1) != 0, // simpleBoolean
            (byte) cursor.getShort(offset + 2), // simpleByte
            cursor.getShort(offset + 3), // simpleShort
            cursor.getInt(offset + 4), // simpleInt
            cursor.getLong(offset + 5), // simpleLong
            cursor.getFloat(offset + 6), // simpleFloat
            cursor.getDouble(offset + 7), // simpleDouble
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // simpleString
            cursor.isNull(offset + 9) ? null : cursor.getBlob(offset + 9) // simpleByteArray
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SimpleEntityNotNullIndexed entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setSimpleBoolean(cursor.getShort(offset + 1) != 0);
        entity.setSimpleByte((byte) cursor.getShort(offset + 2));
        entity.setSimpleShort(cursor.getShort(offset + 3));
        entity.setSimpleInt(cursor.getInt(offset + 4));
        entity.setSimpleLong(cursor.getLong(offset + 5));
        entity.setSimpleFloat(cursor.getFloat(offset + 6));
        entity.setSimpleDouble(cursor.getDouble(offset + 7));
        entity.setSimpleString(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSimpleByteArray(cursor.isNull(offset + 9) ? null : cursor.getBlob(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SimpleEntityNotNullIndexed entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SimpleEntityNotNullIndexed entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SimpleEntityNotNullIndexed entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
